services:
  parser:
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile.parser
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      # network: host
      # args:
      #  - http_proxy=http://127.0.0.1:10808
      #  - https_proxy=http://127.0.0.1:10808
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    #  - "443:443"
    depends_on:
      - web
      # - frontend
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    # - - ./nginx/promapp:/etc/nginx/conf.d/promapp.conf
      - ./media:/var/www/media
    #  - ./backend/staticfiles:/var/www/staticfiles
    #  - /etc/letsencrypt:/etc/letsencrypt:ro
    # - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./alembic/versions:/app/alembic/versions

  db_backup:
    image: postgres:16-alpine
    container_name: db_backup
    restart: no # unless-stopped
    env_file:
      - .env
    volumes:
      - ./backup:/backup
      - ./backup.sh:/app/backup.sh
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    entrypoint: ["/bin/true"] # [ "/bin/sh", "-c" ]
    command:
      - |
        apk add --no-cache curl
        mkdir -p /backup
        echo "0 3 * * * /app/backup.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/root
        touch /var/log/cron.log
        echo ">>> Running initial backup..."
        /app/backup.sh
        echo ">>> Cron started. Next backup at 03:00 daily"
        crond -f -l 2
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  prometheus_data: