# Файлы Python
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Файлы venv
.venv/

# Файлы IDE
.idea/

# Docker
Dockerfile.parser
Dockerfile.web
docker-compose.yml
docker-compose-main.yml
Dockerfile.parser.dockerignore
Dockerfile.web.dockerignore
.dockerignore

# Git
.git
.gitignore

# Other
old-version/
backend
frontend
frontend-old
postgresql
parser_realty
nginx.conf
pg_hba.conf
postgresql.conf
parser.env
run_parser.py
alembic/
alembic.ini