# Файлы Python
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Файлы venv
.venv/

# Файлы IDE
.idea/

# Docker
Dockerfile.parser
Dockerfile.web
docker-compose.yml
Dockerfile.parser.dockerignore
Dockerfile.web.dockerignore

# Git
.git
.gitignore

# Other
web.env
.env
alembic.ini

grafana-config.json
loki-config.yaml
prometheus.yml
promtail-config.yaml

alembic/
frontend/
grafana/
nginx/
media/
web_app/
