FROM python:3.12.3-slim

WORKDIR /app

COPY parser_realty/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["sleep", "infinity"]
CMD ["python", "run_parser.py"]