"""update apartments and bathrooms

Revision ID: 204c809f0b59
Revises: dc3612c94495
Create Date: 2026-02-16 14:19:28.307123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '204c809f0b59'
down_revision: Union[str, Sequence[str], None] = 'dc3612c94495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bathrooms',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )
    op.create_table('apartment_bathroom',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
        sa.Column('bathroom_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['bathroom_id'], ['bathrooms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('apartment_id', 'bathroom_id')
    )
    op.execute('ALTER TABLE apartments DROP CONSTRAINT IF EXISTS apartments_apartment_bathroom_id_fkey')
    op.execute('DROP TABLE IF EXISTS apartment_bathrooms CASCADE')

    op.add_column('apartment_item', sa.Column('brand', sa.String(length=64), nullable=True))

    op.add_column('apartment_item', sa.Column('quantity', sa.Integer(), nullable=True))
    op.execute("UPDATE apartment_item SET quantity = 1")
    op.alter_column('apartment_item', 'quantity', nullable=False)

    op.add_column('apartment_item', sa.Column('price', sa.Integer(), nullable=True))
    op.execute("UPDATE apartment_item SET price = 0")
    op.alter_column('apartment_item', 'price', nullable=False)

    op.drop_index(op.f('ix_apartments_apartment_bathroom_id'), table_name='apartments')
    op.create_index(op.f('ix_apartments_address'), 'apartments', ['address'], unique=False)
    op.drop_column('apartments', 'apartment_bathroom_id')
    op.drop_column('items', 'quantity')
    op.drop_column('items', 'price')
    op.drop_column('items', 'brand')
    op.create_index(op.f('ix_metro_stations_title'), 'metro_stations', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metro_stations_title'), table_name='metro_stations')
    op.add_column('items', sa.Column('brand', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('apartments', sa.Column('apartment_bathroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('apartments_apartment_bathroom_id_fkey'), 'apartments', 'apartment_bathrooms', ['apartment_bathroom_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_apartments_address'), table_name='apartments')
    op.create_index(op.f('ix_apartments_apartment_bathroom_id'), 'apartments', ['apartment_bathroom_id'], unique=False)
    op.drop_column('apartment_item', 'price')
    op.drop_column('apartment_item', 'quantity')
    op.drop_column('apartment_item', 'brand')
    op.create_table('apartment_bathrooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apartment_bathrooms_pkey'))
    )
    op.drop_table('apartment_bathroom')
    op.drop_table('bathrooms')
    # ### end Alembic commands ###
