"""update connection between item and apartments

Revision ID: 28d4af9aa15c
Revises: 204c809f0b59
Create Date: 2026-02-17 12:07:13.123689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d4af9aa15c'
down_revision: Union[str, Sequence[str], None] = '204c809f0b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_apartment_item', 'apartment_item', ['apartment_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_apartment_item', 'apartment_item', type_='unique')
    # ### end Alembic commands ###
