"""add owner table

Revision ID: 3611bdd3dcec
Revises: 5ba7754b8e56
Create Date: 2026-02-20 13:44:07.424591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3611bdd3dcec'
down_revision: Union[str, Sequence[str], None] = '5ba7754b8e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_owner',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id', 'user_id')
    )
    op.drop_constraint(op.f('uq_apartment_item'), 'apartment_item', type_='unique')
    op.drop_constraint(op.f('_user_favorite_uc'), 'favorites', type_='unique')
    op.drop_index(op.f('ix_favorites_apartment_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_apartment_id'), 'favorites', ['apartment_id'], unique=False)
    op.create_unique_constraint(op.f('_user_favorite_uc'), 'favorites', ['user_id', 'apartment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_apartment_item'), 'apartment_item', ['apartment_id', 'item_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('apartment_owner')
    # ### end Alembic commands ###
