"""for apartment_item add uq_apartment_item_fields

Revision ID: 52b63eda3b76
Revises: eafa00c1f580
Create Date: 2026-03-03 12:41:55.980212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b63eda3b76'
down_revision: Union[str, Sequence[str], None] = 'eafa00c1f580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_apartment_item_fields', 'apartment_item', ['apartment_id', 'item_id', 'brand_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_apartment_item_fields', 'apartment_item', type_='unique')
    # ### end Alembic commands ###
