"""add brands table

Revision ID: 5ba7754b8e56
Revises: 28d4af9aa15c
Create Date: 2026-02-19 07:59:12.335438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba7754b8e56'
down_revision: Union[str, Sequence[str], None] = '28d4af9aa15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_title'), 'brands', ['title'], unique=True)

    op.add_column('apartment_item', sa.Column('brand_id', sa.Integer(), nullable=True))

    op.execute("INSERT INTO brands (title, created_at) VALUES ('Unknown', now())")
    op.execute(
        "UPDATE apartment_item SET brand_id = (SELECT id FROM brands WHERE title = 'Unknown') "
        "WHERE brand_id IS NULL"
    )

    op.alter_column('apartment_item', 'brand_id', nullable=False)
    op.create_foreign_key(None, 'apartment_item', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')

    op.alter_column('apartment_item', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    op.drop_column('apartment_item', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_item', sa.Column('brand', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apartment_item', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_apartment_item'), 'apartment_item', ['apartment_id', 'item_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('apartment_item', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('apartment_item', 'brand_id')
    op.drop_index(op.f('ix_brands_title'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
