"""fix orders table

Revision ID: 60925fe520d2
Revises: 52b63eda3b76
Create Date: 2026-03-05 12:01:30.841629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60925fe520d2'
down_revision: Union[str, Sequence[str], None] = '52b63eda3b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('orders', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'wish',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_constraint(op.f('orders_email_key'), 'orders', type_='unique')
    op.drop_constraint(op.f('orders_wish_key'), 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('orders_wish_key'), 'orders', ['wish'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('orders_email_key'), 'orders', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'wish',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('orders', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
