"""[items] add brand, quantity, price

Revision ID: dc3612c94495
Revises: 
Create Date: 2026-02-06 07:03:22.697455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3612c94495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонки как nullable=True (чтобы БД не ругалась на пустые значения)
    op.add_column('items', sa.Column('brand', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('price', sa.Integer(), nullable=True))

    # 2. Проставляем 0 в существующие записи
    op.execute("UPDATE items SET quantity = 0 WHERE quantity IS NULL")
    op.execute("UPDATE items SET price = 0 WHERE price IS NULL")

    # 3. Теперь устанавливаем nullable=False
    op.alter_column('items', 'quantity', nullable=False)
    op.alter_column('items', 'price', nullable=False)

    # Изменение title (оставляем как было)
    op.alter_column('items', 'title',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('items', 'price')
    op.drop_column('items', 'quantity')
    op.drop_column('items', 'brand')
    # ### end Alembic commands ###
