"""update connection contacts

Revision ID: e273aa393229
Revises: e58660d28d1e
Create Date: 2026-04-22 10:07:15.149932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e273aa393229'
down_revision: Union[str, Sequence[str], None] = 'e58660d28d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('apartment_contact',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id', 'contact_id')
    )
    # op.create_unique_constraint('uq_apartment_item_fields', 'apartment_item', ['apartment_id', 'item_id', 'brand_id'])
    op.drop_column('apartments', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('contacts', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint('uq_apartment_item_fields', 'apartment_item', type_='unique')
    op.drop_table('apartment_contact')
    op.drop_table('contacts')
    # ### end Alembic commands ###
