"""add parking and more info for apartments

Revision ID: e58660d28d1e
Revises: 60925fe520d2
Create Date: 2026-04-15 11:47:22.288470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58660d28d1e'
down_revision: Union[str, Sequence[str], None] = '60925fe520d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )
    op.create_table('apartment_parking',
        sa.Column('apartment_id', sa.Integer(), nullable=False),
        sa.Column('parking_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parking_id'], ['parking.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('apartment_id', 'parking_id')
    )

    op.add_column('apartments', sa.Column('contacts', sa.String(length=512), nullable=True))
    op.add_column('apartments', sa.Column('useful_information', sa.String(length=1024), nullable=True))

    op.execute("UPDATE apartments SET contacts = '' WHERE contacts IS NULL")
    op.execute("UPDATE apartments SET useful_information = '' WHERE useful_information IS NULL")

    op.alter_column('apartments', 'contacts', nullable=False)
    op.alter_column('apartments', 'useful_information', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'useful_information')
    op.drop_column('apartments', 'contacts')
    op.drop_constraint('uq_apartment_item_fields', 'apartment_item', type_='unique')
    op.drop_table('apartment_parking')
    op.drop_table('parking')
    # ### end Alembic commands ###
