"""add orders and fix other tables

Revision ID: eafa00c1f580
Revises: 3611bdd3dcec
Create Date: 2026-03-02 13:33:19.911293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafa00c1f580'
down_revision: Union[str, Sequence[str], None] = '3611bdd3dcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('wish', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('wish')
    )
    op.create_index(op.f('ix_orders_apartment_id'), 'orders', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('apartment_availability', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_apartment_availability_reservation_id'), 'apartment_availability', ['reservation_id'], unique=False)
    op.create_foreign_key(None, 'apartment_availability', 'orders', ['reservation_id'], ['id'], ondelete='SET NULL')
    op.alter_column('apartments', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'apartment_availability', type_='foreignkey')
    op.drop_index(op.f('ix_apartment_availability_reservation_id'), table_name='apartment_availability')
    op.drop_column('apartment_availability', 'reservation_id')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_apartment_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
